name: autofix.ci

on:
  push:        # runs on every commit to any branch

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "npm"

      - run: npm ci
      - run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "fix(format): autofix code style"
