name: lighthouse.ci

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci && npm install -g @lhci/cli@0.15.x
      - run: npm run build
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
