name: Lint

on:
  push: # runs on every commit to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5

      - run: npm ci
      - run: npm run lint
